### ISSUE TITLE
Is it wise to use Angular on top of all the other libs?

### ISSUE THREAD

**Issue by PeterKnight** [ImageFlow/imageflow-prototype#10]
Is utilising angular.js part of the long term plan? Isn't this a rather weighty choice to opt for when WordPress is already including things like backbone / jquery / jquery-ui / underscore etc etc in the admin screens? Adding angular.js seems like overkill to me. Most devs haven't grasped WP's use of backbone yet, I think adding angular into the mix overcomplicates things.

**Comment by melchoyce** [comment]
Pretty sure angular is just for the prototype.

**Comment by aymanalzarrad** [comment]
The intention of using Angular here is just to have a better/faster prototyping process and make it as close as possible  to the real thing for the user testing process. I don't believe its gonna be used when building the feature plugin as that will definitely be an overkill.

**Comment by PeterKnight** [comment]
Got it! :)
