### ISSUE TITLE
Insert from URL needs proper heading

### ISSUE THREAD

**Issue by mor10** [ImageFlow/imageflow-prototype#12]
On the Upload File page the second section (Insert from URL) needs a proper heading or some form of clear separator. Currently the fields appear as if they are related to the uploader which causes confusion, especially once the image is uploaded. The user says "Oh, I forgot to add a title on the previous screen!"

![screen shot 2015-02-12 at 10 07 01 am](https://cloud.githubusercontent.com/assets/1132200/6173765/210c00fe-b29f-11e4-91c4-a00a78624c35.png)

**Comment by teamAris** [comment]
All set in 7657501c5571b756da0dbf4633cdd7c905209fc2
