### ISSUE TITLE
Spelling error on Upload File 3rd stage

### ISSUE THREAD

**Issue by mor10** [ImageFlow/imageflow-prototype#13]
"You are _new_ choosing an image" should probably "You are _now_ choosing an image". 

![screen shot 2015-02-12 at 10 10 14 am](https://cloud.githubusercontent.com/assets/1132200/6173802/76287798-b29f-11e4-99bc-751cf2ef08a6.png)

**Comment by teamAris** [comment]
All set in commit 7657501c5571b756da0dbf4633cdd7c905209fc2
