### ISSUE TITLE
Clicking the Add Media button after image insert does not work

### ISSUE THREAD

**Issue by mor10** [ImageFlow/imageflow-prototype#16]
Once an image is inserted the Add Media button does not perform an action. To get back to the Grid you have to Move to Trash or Publish. 

For testing purposes the ideal scenario would be for the Add Media button to open the Grid and allow the adding of an additional image.

Alternately for testing purposes clicking the Add Media button after an image has been added should clear the original image and start the process over.

This addresses the common scenario that the tester wants to do something again immediately after adding the first image.

**Comment by aymanalzarrad** [comment]
This is related to #17 
I will be commiting a fix soon
