### ISSUE TITLE
Full width view not including the uploaded image

### ISSUE THREAD

**Issue by aymanalzarrad** [ImageFlow/imageflow-prototype#34]
The full width view is not including the uploaded image even if the image is selected

**Comment by teamAris** [comment]
Good catch, another leftover from before we had a single app. What's easier/faster @royboy789: offsetting the images unless an 'uploaded' variable has been flipped, or actually adding the new image to the images array?

**Comment by aymanalzarrad** [comment]
I was looking into this, and I think both the grid and the full width should display the uploaded image after the upload is successful. 
Please correct me if I'm wrong, but I think it's confusing for the users to not have an image that was uploaded a second ago in the grid just because they have navigated between grid<--->full-width. 
I believe this might have a negative impact while testing.
We could instead reset the process to it's initial state once the user closes the modal (as we already have it with the selected images), in-case we wanna repeat the process.

**Comment by teamAris** [comment]
You're right, this is a problem. Another hold over from the separate app
approach. I don't think the uploaded image needs to be persistent across
modal open/close, but it should definitely be persistent per modal
'session'.

I don't think it has to stop testing, but testers need to be avoid
full-width after upload at the moment.
